databases:
  - name: sirecup-db
    databaseName: sirecup
    plan: free

services:
  - type: web
    name: sirecup
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sirecup-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
